@baseUrl = http://localhost:30027

###


###

GEt {{baseUrl}}/commentaires/ItTakesTwo     


###
POST {{baseUrl}}/commentaires
Content-Type: application/json

{
    "game":"Battlefield 2042",
    "message":"",
    "expediteur": "k1"

}
###
PUT {{baseUrl}}/commentaires/3

###
PUT {{baseUrl}}/commentaires/23


###
POST {{baseUrl}}/liked
Content-Type: application/json

{
    "jeu":"Battlefield 2042",
    "expediteur": "k1",
    "evaluation":10

}
###
GET {{baseUrl}}/liked/k1

###
GET {{baseUrl}}/liked/game/New World

###
GET {{baseUrl}}/liked/votant/New World

